## APIHolders 模块
APIHolders:
  ## 监听路径
  # 必须以 / 开头，ph查询特定Placeholder，status查询服务器状态。
  # 留空表示不启用
  path:
    ph: "/api/placeholder"
    status: "/api/status"

  ## 跨域请求（CORS）标头
  # 在前端应用中，浏览器会限制跨域请求，即只允许下面配置的域名和同域名获取数据。
  # 这个设置具体控制Access-Control-Allow-Origin标头的内容，它可以为：
  # 1. "*"：允许所有域名；
  # 2. "null"：只允许同域名（此用法已被MDN不推荐使用）；
  # 3. 单个具体域名，例如 "https://example.com"：只允许该域名获取数据。
  cors-allowed: "*"

  ## 名单模式
  # 启用即白名单，只允许查询匹配的；否则为黑名单，允许查询全部不匹配的（不推荐）
  white-mode: true

  ## 限制查询的 Placeholders 名单列表
  # 无需携带「%」，支持两种写法：
  # 1. 普通字符串，全匹配（忽略大小写）
  # 2. "regex:正则表达式"  正则匹配
  ph_list:
    - "player_name"
    - "server_online"
    - "regex:server_.*"

## 配置文件版本
version: 000001
# 如无必要请勿修改